server:
  port: 8083
spring:
  application:
    name: cart-service
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  datasource:
    url: jdbc:mysql://localhost:3306/cart-service
    username: root
    password: 0665.0189.59
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
