stages:
  - build

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

build:
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - mkdir -p $HOME/.docker
    - echo "$DOCKER_CONFIG_YML" > $HOME/.docker/config.yml
    - mvn $MAVEN_CLI_OPTS clean install jib:build


