stages:
  - build
build:
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - mkdir -p $HOME/.docker
    - echo "$DOCKER_CONFIG_YML" > $HOME/.docker/config.yml
    - mvn clean install jib:build


