docker-login:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - cat $DOCKER_CONFIG/config.json


maven-build:
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - mvn clean install jib:build -X
